### ISSUE TITLE
Check build status for binaries ready to be installed

### ISSUE THREAD

**Issue by Try2Code** [conda-forge/cdo-feedstock#108]
Hi!

A user contacted me that the cdo binary for MacOS is still version 1.9.9 when searched/updated with conda. Is there any webpage where we can check which binaries are available?

**Comment by akrherz** [comment]
The [anaconda website](https://anaconda.org/conda-forge/cdo/files) lists them.  The [README.md](https://github.com/conda-forge/cdo-feedstock) on the repo lists the most recent one.

**Comment by Try2Code** [comment]
@akrherz thx a lot for the support :pray:
