### ISSUE TITLE
Arch migration 

### ISSUE THREAD

**Issue by aaronspring** [conda-forge/cdo-feedstock#109]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue: i would like to run cdo and python-cdo on arm64. Currently only built for linux64 and osx64. as in https://github.com/conda-forge/esmf-feedstock/issues/74

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by akrherz** [comment]
I am unsure why, attempting osx arm migration in #110

**Comment by akrherz** [comment]
First glance, appears `ossuuid` package does not exist for arm, hmmm

**Comment by zklaus** [comment]
I think @akrherz is spot on. I am trying the `ossuuid` migration in conda-forge/ossuuid-feedstock#7, but in parallel @akrherz has started working on the migration to osx-arm64 by swapping out `ossuuid` for `libuuid`, which I think is a good idea anyway.

**Comment by akrherz** [comment]
Awaiting main branch build after merger of #119

**Comment by akrherz** [comment]
Build should be available on conda-forge CDN shortly.
