### ISSUE TITLE
Failure linking on OS X

### ISSUE THREAD

**Issue by ocefpaf** [conda-forge/cdo-feedstock#15]
`cdo 1.7.2` fails when adding any extra dependency on `OS X`. See https://github.com/conda-forge/cdo-feedstock/pull/8#issuecomment-260133847

**Comment by aidanheerdegen** [comment]
Given that thread safe HDF5 was a block for this, can there be some progress now?

https://github.com/conda-forge/hdf5-feedstock/pull/48

**Comment by ocefpaf** [comment]
> Given that thread safe HDF5 was a block for this, can there be some progress now?

We can try but I don't recall the thread safety being the only issue.
