### ISSUE TITLE
Build cdo on Windows

### ISSUE THREAD

**Issue by ocefpaf** [conda-forge/cdo-feedstock#2]
There are no Windows builds at the moment

**Comment by Try2Code** [comment]
Just as a side note: A cygwin-based precompiled binary is available from the main CDO- webpage: https://code.mpimet.mpg.de/projects/cdo/files

**Comment by ocefpaf** [comment]
Good to know. We can try `msys2`, which is similar to cygwin but shipped by the default channel.

**Comment by Try2Code** [comment]
what is msys2 ?

**Comment by ocefpaf** [comment]
It is similar to `cygwin`. A *nix-like environment that may facilitate to compile `cdo` on Windows.

**Comment by Try2Code** [comment]
If you think I could help, just let me know

**Comment by andreas-h** [comment]
Shouldn't it be possible to simply download the Cygwin64 binary from https://code.mpimet.mpg.de/projects/cdo/files and put that into a conda package?  The only issue I see is the cygwin dependencies.  Unfortunately, I don't really have any experience with Windows builds.  Any ideas?

**Comment by ocefpaf** [comment]
Re-packing is possible but with `msys2` in the default channel we should probably use that. I'll give it a shot but I am terrible with Windows.

**Comment by Try2Code** [comment]
@ocefpaf 👍 

IMO including cygwin is not an option - messing around with _one_ posix-windows-bridge is punishment enough

**Comment by Try2Code** [comment]
regarding using CDO on windows: Can we relay on the Linux Subsystem of Windows10? Since it's an ubunty system `conda` should work anyway ...

**Comment by ocefpaf** [comment]
I guess we can. Keeping this issue open if someone wants to address a native build it not a problem. But yeah, we should probably just recommend the WLS.

**Comment by Try2Code** [comment]
that's what I usually do on user requests. ppl seem to be happy with it.

**Comment by ocefpaf** [comment]
In that case, if you want to close the issue I'm ok with that. Folks who want to try a native build in the future will find the problem without this issue.
