### ISSUE TITLE
netCDF root directory not set on macOS

### ISSUE THREAD

**Issue by pgierz** [conda-forge/cdo-feedstock#29]
Hi,

when doing a `conda install cdo` on mac, I get the following error when trying to use cdo and netcdf files:

```
Unsupported file type (library support not compiled in)
To create a CDO application with NetCDF support use: ./configure --with-netcdf=<NetCDF root directory>
```

Likely, the configure recipie isn't correct for mac, since it is missing some parts that appear to be set in the `uname` check. I haven't been using conda very long; and while I would try to fix this on my own, I'm not sure where exactly to start.

**Comment by ocefpaf** [comment]
The Mac compilation is completely broken. See https://github.com/conda-forge/cdo-feedstock/issues/15

Unfortunately I do not own a Mac nor I understand its details to fix that.

Closing this as a duplicated of #15. If you know a way to fix that please comment on #15.
