### ISSUE TITLE
netcdf support does not work

### ISSUE THREAD

**Issue by pgierz** [conda-forge/cdo-feedstock#34]
I am currently unable to install cdo with netcdf support, and when using the cdo installed via `conda install cdo`, I obtain errors such as:

```
cdo seltimestep: Open failed on >/Volumes/Research_HD/cosmos-aso-wiso/Eem130-S2/post/mpiom/Eem130-S2_mpiom_main_THO_levels_6-100_vertmean_months_678_yearmean.nc<
Unsupported file type (library support not compiled in)
To create a CDO application with NetCDF support use: ./configure --with-netcdf=<NetCDF root directory> ...
```

I suspect that the recipie must be changed to enable netcdf, but I am unsure how to do this,

**Comment by pgierz** [comment]
Sorry, this is a dupilicate of a previously stated issue (from what I can tell, #8)

**Comment by ocefpaf** [comment]
Are you on OS X? If so we don't really have a fully "working" version there.
