### ISSUE TITLE
self-define the parameters of configure?

### ISSUE THREAD

**Issue by lovechang1986** [conda-forge/cdo-feedstock#35]
Hi, thanks for this wonderful work.

Here, I has a question that how can i set the configure paramete like --enable-cgribex=no?

While if the file contain both grib1 and grib2, cdo would like to choose cgribex to handle grib1 and use grib_api for grib2. That's could be some mistake. So I want to set disable cgribex.

ps:
[cdo1](https://code.mpimet.mpg.de/boards/1/topics/1171#message-1175)
[cdo2](https://code.mpimet.mpg.de/boards/1/topics/713#message-716)

**Comment by ocefpaf** [comment]
I'm not an expert `cdo` user to decide if ` --enable-cgribex=no` should be our default or not, but if you want to rebuilt it locally that way you need to add that line [here](https://github.com/conda-forge/cdo-feedstock/blob/master/recipe/build.sh#L15-L25).

Closing this b/c `--enable-cgribex=no` does not seem to be the recommended default. (Please correct me if I am wrong @Try2Code.)

**Comment by Try2Code** [comment]
IMO `--enable-cgribex=no` is a bad default. cgridex should be enabled (default setting), since it is the only native output format of CDO (GRIB1). This switch should only be used if (and only if) you want to use the GRIB1 encoding of eccodes (which is 10x slower)

hth

**Comment by ocefpaf** [comment]
Thanks for the clarification @Try2Code!
