### ISSUE TITLE
Request to update cdo feedstock to v1.9.7.1

### ISSUE THREAD

**Issue by agstephens** [conda-forge/cdo-feedstock#61]
Please can you update the cdo feedstock to v1.9.7.1. We have users requesting this on the JASMIN environment. Thanks :-)

**Comment by Try2Code** [comment]
hi! 
there already is a pull request for this (#60) but the back-end seem to have trouble atm.

**Comment by ocefpaf** [comment]
> hi!
> there already is a pull request for this (#60) but the back-end seem to have trouble atm.

Looking into it today. (It feel fell through the cracks of my ever growing TODO list.)

**Comment by ocefpaf** [comment]
Done! Thanks for the ping. #60 was merged.

**Comment by agstephens** [comment]
Thanks @ocefpaf , That's great.
