### ISSUE TITLE
Switch from ossuuid to libuuid?

### ISSUE THREAD

**Issue by bouweandela** [conda-forge/cdo-feedstock#83]
This package depends on `ossuuid`, which cannot be installed at the same time as `libuuid`, used by many other packages such as `matplotlib` (see e.g. https://github.com/conda-forge/libcf-feedstock/issues/20, https://github.com/conda-forge/cmor-feedstock/issues/9, https://github.com/PCMDI/cmor/issues/458). Would it be possible to switch to `libuuid`?

It looks like you might also encounter this issue when adding `cmor` as a dependency again in #79, since that package has now switched.

```
ClobberWarning: This transaction has incompatible packages due to a shared path.
  packages: conda-forge/linux-64::libuuid-2.32.1-h14c3975_1000, conda-forge/linux-64::ossuuid-1.6.2-hf484d3e_1000
  path: 'lib/libuuid.a'


ClobberWarning: This transaction has incompatible packages due to a shared path.
  packages: conda-forge/linux-64::libuuid-2.32.1-h14c3975_1000, conda-forge/linux-64::ossuuid-1.6.2-hf484d3e_1000
  path: 'lib/libuuid.la'


ClobberWarning: This transaction has incompatible packages due to a shared path.
  packages: conda-forge/linux-64::libuuid-2.32.1-h14c3975_1000, conda-forge/linux-64::ossuuid-1.6.2-hf484d3e_1000
  path: 'lib/libuuid.so'


ClobberWarning: This transaction has incompatible packages due to a shared path.
  packages: conda-forge/linux-64::libuuid-2.32.1-h14c3975_1000, conda-forge/linux-64::ossuuid-1.6.2-hf484d3e_1000
  path: 'lib/pkgconfig/uuid.pc'
```

**Comment by ocefpaf** [comment]
These are warnings and not errors. Also, please add the required debug information from the issue template. I do not get those warnings when trying that and I cannot guide you any further without that information.
