### ISSUE TITLE
cannot load libjpeg.so.9

### ISSUE THREAD

**Issue by ywangd** [conda-forge/cdo-feedstock#9]
I installed cdo with Python 2.7.12, anaconda 64-bit, Redhat Linux 7. The installation went OK. But as soon as I run cdo, it reports the following error
```
cdo: error while loading shared libraries: libjpeg.so.9: cannot open shared object file: No such file or directory
```
I checked the `lib` directory in anaconda installation and only found `libjpeg.so.8` not 9. Do I need to install the library separately or is there any easy fix? Thanks!

**Comment by ywangd** [comment]
Nevermind, I upgrade libjpeg to version 9 with `conda update -c conda-forge jpeg` and now cdo works.

**Comment by ocefpaf** [comment]
@ywangd note that conda should do the right thing and install the right `jpeg 9*` for you. However, make sure you have the latest `conda` and that you added the `conda-forge` channel on top of `defaults` so you can take advantage of the channel preference feature.

**Comment by wuchao** [comment]
sudo ranlib /usr/local/lib/libjpeg.a
sudo ldconfig /usr/local/lib

**Comment by herleeyandi** [comment]
@ocefpaf  Hi I have same problem when installing caffe in anaconda 3. The file of libjpeg.so.9 does exist in anaconda but during caffe compilation it can not find by opencv. How do I fix this?, How do we make change and make sure that conda-forge is in the top channel?

**Comment by ocefpaf** [comment]
@herleeyandi please take a look at https://conda-forge.org/docs/conda-forge_gotchas.html

**Comment by sunyanfeng** [comment]
@herleeyandi I have met the same problem, Have you solved it yet?

**Comment by herleeyandi** [comment]
@sunyanfeng I am still stuck in this problem and not continue it anymore. I believe the problem lies on the caffe can not find your installed libjpeg in anaconda3. When you point it in there, there will be another problem raised. I forgot about the error because it a month ago. Sorry I can not help you.

**Comment by ujwalp15** [comment]
conda update -c conda-forge jpeg, this no longer updates it, for some unknown reason
